name: ci-test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0 # get all branches so that we can check out main to compare lint scores

    - name: Run make ci-build in dev container
      uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8
      with:    
        # TODO - cache dev container image
        push: never
        env: |
          GITHUB_BASE_REF
        runCmd: |
          echo -e "Running ci-build for ref:$GITHUB_BASE_REF\n\n"
          make install-requirements

          echo -e "\n\n--------------------------------------------------------------------------------\n\n"
          ./scripts/ci-lint.sh

          echo -e "\n\n--------------------------------------------------------------------------------\n\n"
          make test


